### ISSUE TITLE
Which is the best way for the tutorial rendering?

### ISSUE THREAD

**Issue by MatteoRobbiati** [qibogang/qibogang.github.io#10]
For now the situation is the following:

- we have a `qiboteam/tutorials` repo in which `jupyter notebooks` are uploaded without the outputs;
- we have a `tutorials` page in the website which is built thanks to a rendering of a `*.md` version of the same notebooks.

The idea is to build a mechanism for:

1. compile the `no-output.ipynb` in order to return the outputs;
2. convert the `with-output.ipynb` to a markdown file or whatever we want to use in the site rendering;
3. showing the output on the site.

**Comment by MatteoRobbiati** [comment]
Moreover, in order to show beautiful notebooks on the page, I am wondering about the best method for customizing the markdown style while (or post?) the rendering done using `nextjs`. An example can be [this](https://github.com/markdown-it/markdown-it).

**Comment by AleCandido** [comment]
> customizing the markdown style while (or post?)

Definitely "post":
1. Next.js will create the HTML/JS bundle (essentially, transpile your md code to HTML)
2. you want to style the result with CSS, possibly reusing the same of the rest of the website, plus a few dedicated options

**Comment by MatteoRobbiati** [comment]
> Definitely "post":
> 
>     1. Next.js will create the HTML/JS bundle (essentially, transpile your md code to HTML)
> 
>     2. you want to style the result with CSS, possibly reusing the same of the rest of the website, plus a few dedicated options

I agree with the strategy but, before acting more precisely on the `css` file, I was doing some experiments with some `react` applications. For example, I have just find this one: [`react-jupyter-notebook-viewer`](https://github.com/mtetik98/react-jupyter-notebook-viewer), which I find interesting in terms of style.

The problem with this is that it seems to "overload" my `css` style, changing for example the navbar and the footer layout (acting on images and not on the writings).
A proof follows:

![proof](https://user-images.githubusercontent.com/62071516/202697238-5382eef0-9b89-41c2-b6f5-333f41c8d796.png)


Before going on this research, I wanted a confrontation about it @AleCandido: is my current investigation useful? Or should I proceed as we said?

**Comment by AleCandido** [comment]
You can definitely keep going, that is perfectly fine.

> For example, I have just find this one: [`react-jupyter-notebook-viewer`](https://github.com/mtetik98/react-jupyter-notebook-viewer), which I find interesting in terms of style.

![image](https://user-images.githubusercontent.com/10830876/202697983-02bd39a4-edb1-46be-8454-5e83ee70b465.png)
![image](https://user-images.githubusercontent.com/10830876/202698287-094d9cd8-a70a-404c-b29b-41915917d98b.png)


About this package: it is worrisome that is the personal project of a random guy, that worked on it a bit in June, and then stopped for 5 months.
If you like the result, what you can do is to draw inspiration from his code, and write your own components in this repo. It is a relatively small amount of code, so you can reproduce it and customize :)

**Comment by MatteoRobbiati** [comment]
> You can definitely keep going, that is perfectly fine.
> 
> > For example, I have just find this one: [`react-jupyter-notebook-viewer`](https://github.com/mtetik98/react-jupyter-notebook-viewer), which I find interesting in terms of style.
> 
> ![image](https://user-images.githubusercontent.com/10830876/202697983-02bd39a4-edb1-46be-8454-5e83ee70b465.png) ![image](https://user-images.githubusercontent.com/10830876/202698287-094d9cd8-a70a-404c-b29b-41915917d98b.png)
> 
> About this package: it is worrisome that is the personal project of a random guy, that worked on it a bit in June, and then stopped for 5 months. If you like the result, what you can do is to draw inspiration from his code, and write your own components in this repo. It is a relatively small amount of code, so you can reproduce it and customize :)

Ok, you are right. Thank you!

**Comment by MatteoRobbiati** [comment]
I think this issue can be closed after merging #15.

**Comment by AleCandido** [comment]
Ok, #15 is closed, there is already another PR doing this (#6), and this issue switched topic from JN to markdown style.

I will close this to clean-up, since:
- markdown styling has been done in #15 (can be improved, but in dedicated issues/PRs)
- JN will keep being discussed in #3
