### ISSUE TITLE
Rendering of LaTeX in nextjs + react app

### ISSUE THREAD

**Issue by MatteoRobbiati** [qibogang/qibogang.github.io#14]
As the title says.

**Comment by AleCandido** [comment]
Use KaTeX, or some package providing it for you :)
(I would have expected mdx renderers to take care of this themselves)

**Comment by AleCandido** [comment]
Btw, it seems that MathJax caugth up with KaTeX performances in v3 (v2 was horribly slow):

https://www.intmath.com/cg5/katex-mathjax-comparison.php

**Comment by MatteoRobbiati** [comment]
I think that this can be close after merging #15.

**Comment by AleCandido** [comment]
> I think that this can be close after merging #15.

It is possible to link PRs to issues, selecting them in the right column :)
![image](https://user-images.githubusercontent.com/10830876/205037636-a35b4b46-b37d-4558-8c20-6edca4351fa6.png)

**Comment by MatteoRobbiati** [comment]
> > I think that this can be close after merging #15.
> 
> It is possible to link PRs to issues, selecting them in the right column :) ![image](https://user-images.githubusercontent.com/10830876/205037636-a35b4b46-b37d-4558-8c20-6edca4351fa6.png)

Oh, nice! Thank you :)
